### PR TITLE
DAT-3085 Update collapsed/uncollapsed infobox tests

### PR DESCRIPTION
**Pull request by dianafa**
https://wikia-inc.atlassian.net/browse/DAT-3085

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues:
* MINOR 1 minor
* INFO 1 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* INFO [Complete the task associated to this TODO comment.](https://github.com/Wikia/selenium-tests/blob/b7cdda4b4e61cbe3ad8833371271df239dc51207/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/PortableInfoboxObject.java#L79) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1135)
* MINOR [Define a constant instead of duplicating this literal "margin" 4 times.](https://github.com/Wikia/selenium-tests/blob/b7cdda4b4e61cbe3ad8833371271df239dc51207/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/PortableInfoboxObject.java#L275) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)

**Comment by tomasznapieralski** [comment]
LGTM

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues:
* MINOR 1 minor
* INFO 1 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* INFO [Complete the task associated to this TODO comment.](https://github.com/Wikia/selenium-tests/blob/b7cdda4b4e61cbe3ad8833371271df239dc51207/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/PortableInfoboxObject.java#L79) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1135)
* MINOR [Define a constant instead of duplicating this literal "margin" 4 times.](https://github.com/Wikia/selenium-tests/blob/b7cdda4b4e61cbe3ad8833371271df239dc51207/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/PortableInfoboxObject.java#L275) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)

**Comment by nikodamn** [comment]
:shipit:

**Pull request merged**
