### PR TITLE
Globalshortcuts test fix

### PR DESCRIPTION
**Pull request by ludwikkazmierczak**
Deleted "noise" from a testcase code
Added lombok lib to handle lazy getters on *Page* classes

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Remove this unused import 'org.openqa.selenium.support.PageFactory'.](https://github.com/Wikia/selenium-tests/blob/1aa2c303a6973068021c591cebe8bcec349fbbb2/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/HomePageObject.java#L13) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by tomasznapieralski** [comment]
Branch is not compiling

**Comment by tomasznapieralski** [comment]
KeyboardShortcutsModal is not extending WikiBPO

**Comment by tomasznapieralski** [comment]
move class that represents Page to elements > oasis > pages

**Comment by tomasznapieralski** [comment]
LGTM

**Pull request merged**
