### PR TITLE
ADEN-3731 add ubisoft tracking

### PR DESCRIPTION
**Pull request by v3rth**

### CODE REVIEW

**Comment by nandy-andy** [comment]
LGTM

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Define a constant instead of duplicating this literal "src/test/resources/adsResources/wikia_skin_left.png" 9 times.](https://github.com/Wikia/selenium-tests/blob/79b3b9ee18aeab195bf4c4a8a4f41018449354b8/src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java#L174) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AS1192)

**Comment by nikodamn** [comment]
@v3rth @nandy-andy is this PR still valid or we can close it?

**Comment by nandy-andy** [comment]
It still waits for business decision: [ADEN-3731](https://wikia-inc.atlassian.net/browse/ADEN-3731)

**Comment by nandy-andy** [comment]
The project has been sunset. Closing PRs.

**Pull request closed without merging**
