### PR TITLE
Add failed test annotations

### PR DESCRIPTION
**Pull request by nikodamn**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 4 issues:
* MINOR 4 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Define a constant instead of duplicating this literal "image" 8 times.](https://github.com/Wikia/selenium-tests/blob/cbd5f02e6ea7b7581f49b4aa428ee5419fb99eea/src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleFeaturesCRUDTestsUser.java#L50) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "image" 3 times.](https://github.com/Wikia/selenium-tests/blob/cbd5f02e6ea7b7581f49b4aa428ee5419fb99eea/src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleSourceModeTests.java#L187) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "\n</gallery>" 3 times.](https://github.com/Wikia/selenium-tests/blob/cbd5f02e6ea7b7581f49b4aa428ee5419fb99eea/src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleSourceModeTests.java#L195) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "image" 4 times.](https://github.com/Wikia/selenium-tests/blob/cbd5f02e6ea7b7581f49b4aa428ee5419fb99eea/src/test/java/com/wikia/webdriver/testcases/blogtests/BlogFeaturesTests.java#L45) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)

**Comment by tomasznapieralski** [comment]
Do you think this comment in necessary?
`comment = "Test manually"`

**Comment by drets** [comment]
:+1: 

what value has "Test manually" comment?

**Comment by nikodamn** [comment]
@tomasznapieralski @drets  I'm open to suggestions. So, do you suggest that the name of the related ticket is enough?

**Comment by tomasznapieralski** [comment]
i suggest leaving it without comment, just:
`@RelatedIssue(issueID = "MAIN-6072")`

**Comment by drets** [comment]
LGMT :+1:

**Comment by Archbold** [comment]
@tomasznapieralski  and @drets  It's important to add the comments "test manually" as this indicates to the next jenkins duty person that  the automated test is failing but that the product still needs to be tested manually. Please put the "Test manually@ comments back.

**Comment by tomasznapieralski** [comment]
IMO if test is linked to ticket, it means that something is wrong and i need to check it manually.
Comments should describe as @drets said, more details 'why' test is marked.

**Comment by tomasznapieralski** [comment]
i.e. i can warn others that test returns false results from time to time

**Comment by tomasznapieralski** [comment]
but comment like 'Test manually' is obvious

**Comment by Archbold** [comment]
@tomasznapieralski  and @drets A related ticket ID can mean either a product code defect or a automation code defect. The Jenkins duty perosn needs to know whether he/she needs to test the product code manually.

**Comment by drets** [comment]
Correct me if I am wrong: in both cases (doesn't matter if it's a product code defect or an automation code defect) Jenkins duty person should test feature manually.

**Comment by tomasznapieralski** [comment]
@drets :+1: that's what i think

**Comment by Archbold** [comment]
@tomasznapieralski  and @drets  Here is the reasoning: Example:- If the product code to load an image has an unfixed defect which means that it is not possible to load an image (and the automated test code has no defects and has the product code relatedissue ID) then there is no requirement to test manually as we know the manual test will fail.

If the automated test code has a defect (so the test fails) but the product code has no defect then we need to test manually to ensure that it still has no product code defect.

**Comment by tomasznapieralski** [comment]
IMO:
When code is broken, not the test, we should add comment like 'tested functionality is broken' or/and disable test and in linked ticket add comment like 'after this ticket is done, please enable this (link) test'.
Reading this i will skip manual check of this functionality, because i know that it is broken already.

When test is broken, not the code, live it without comment.
I will check that functionality, because i don't know why the test fails

What do you think @Archbold @drets ?

**Comment by Archbold** [comment]
@tomasznapieralski and @Drets "Test Manually" or "do not test manually": These statements are unambiguous.  
Let's continuing this discussion in the next QM meeting. Ie the meanwhile we will continue to use  "Test Manually" and "do not test manually" as this is working very well for those who are doing the App Jenkins duty.

**Comment by tomasznapieralski** [comment]
ok, added point to agenda

**Pull request merged**
