### PR TITLE
Aden 2497

### PR DESCRIPTION
**Pull request by ludwikkazmierczak**
Rewriten IVW2 tests to use provided browser object instead of JSoup

### CODE REVIEW

**Comment by drets** [comment]
Why introduce new browser? Why don't use phantomjs and ghostdriver for example?

**Comment by justnpT** [comment]
+1 to the driver question

**Comment by ludwikkazmierczak** [comment]
@drets @justnpT We are not introducing a new browser - HTMLUNIT was there when I came here. (look at the NewDriverProvider class) Why not phantomjs? - phantom is not working by default on every environment, we have to either install it or include an actual executable files (for Mac, Win and Ubuntu). While getting phantomJS to work smoothly would be one of a Q4 goals, for now, we use what we already have.

The version bump to 2.18 is caused by ssl certs conflict between httpclient in v 4.5 and html-unti in version, 2.17 (included into 2.47.1 selenium htmlunit-driver lib)

one more note: ghostdriver is unfortunately a dying project right now due to lack of a core maintainer, so I might choose another headless browser (other then phantomjs) as our day-to-day tool.

**Comment by ludwikkazmierczak** [comment]
@drets @justnpT Any other thing that needs to be clarified? ;)

**Comment by drets** [comment]
@ludwikkazmierczak Thanks for explanation!

> one more note: ghostdriver is unfortunately a dying project right now due to lack of a core maintainer, so I might choose another headless browser (other then phantomjs) as our day-to-day tool.

Yep, _SeleniumConf 2015_ announced it officially.

My big caveat for using `HTMLUNIT`:

> None of the popular browsers uses the javascript engine used by HtmlUnit (Rhino). If you test javascript using HtmlUnit the results may differ significantly from those browsers.
Source: https://code.google.com/p/selenium/wiki/HtmlUnitDriver

and since mobile users are our biggest audience and on Front end we use `Ember.js` I would think about:

> Headless browsers that have JavaScript support via an emulated DOM generally have issues with some sites that use more advanced/obscure browser features, or have functionality that has visual dependencies (e.g. via CSS positions and so forth)
Source: https://gist.github.com/evandrix/3694955

For this particular test on Oasis we can use `HTMLUNIT`, so LGTM :+1:

One more question:
> phantomJS to work smoothly would be one of a Q4 goals

What the reason to do it if ghostdriver is the main driver for phantomJS?
Are we going to use phantomJS outside of Selenium (e.g. http://casperjs.org/)?

**Comment by ludwikkazmierczak** [comment]
I haven't decided yet how we are going to tackle headless browsers in general. As you all know, I want to make headless browsing a main tool for running test automation on dev env. I don't know yet if we are going to use phantomJS outside of Selenium tests, or we are going to switch to another headless browser, with is more JAVA friendly.

**Comment by justnpT** [comment]
Sure, just remember to keep people updated on these decision not through
few words told to someone / some group, but through newsletter / some
document sent to qa or better to wikia-engineering as more developers are
writing / reviewing selenium tests these days.

On Fri, Oct 2, 2015 at 11:36 AM, Ludwik <notifications@github.com> wrote:

> Merged #889 <https://github.com/Wikia/selenium-tests/pull/889>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wikia/selenium-tests/pull/889#event-425088532>.
>



-- 
Michał Nowierski
QA Team Engineer
Wikia inc.
ul. Abpa Baraniaka 6, 61-245 Poznań, Poland

**Pull request merged**
