### PR TITLE
map test disabled as functionality will be deprecated

### PR DESCRIPTION
**Pull request by Archbold**

### CODE REVIEW

**Comment by tomasznapieralski** [comment]
IMO we should remove this test from Jenkins, not disabling it in our code

**Comment by Archbold** [comment]
@tomasznapieralski good topic to discuss in the next QM meeting . Please add to the agenda for 14-Dec-15

**Comment by drets** [comment]
LGTM

**Comment by tomasznapieralski** [comment]
@Archbold point added to agenda, let's wait with this PR till QM meeting on 14-Dec-15 then

**Comment by tomasznapieralski** [comment]
What? @WikiaJenkins closed ticket?? @ludwikkazmierczak

**Comment by tomasznapieralski** [comment]
ah i see, this PR was to preview!

**Comment by tomasznapieralski** [comment]
@Archbold this test is already disabled
see https://github.com/Wikia/selenium-tests/blob/master/src/test/java/com/wikia/webdriver/testcases/interactivemapstests/NonSpecificMapTests.java#L123

**Comment by Archbold** [comment]
@tomasznapieralski Okey dokey I will close the ticket without merging. Thanks

**Pull request closed without merging**
