### PR TITLE
Remove random

### PR DESCRIPTION
**Pull request by ludwikkazmierczak**
Removed all openRandomArticle Usages, and removed `openRandomArticle()` method ;)

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues:
* MINOR 2 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Remove this unused import 'com.wikia.webdriver.common.contentpatterns.PageContent'.](https://github.com/Wikia/selenium-tests/blob/6be9a78ca033dd6229cf97b6b13913af789ad487/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wikipage/WikiArticlePageObject.java#L3) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AUselessImportCheck)
* MINOR [Remove this unused import 'com.wikia.webdriver.pageobjectsfactory.pageobject.WikiBasePageObject'.](https://github.com/Wikia/selenium-tests/blob/6be9a78ca033dd6229cf97b6b13913af789ad487/src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Layout.java#L6) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by tomasznapieralski** [comment]
remove src/test/resources/ChromeDriver/chromedriver_win32/chromedriver.exe

**Comment by tomasznapieralski** [comment]
https://github.com/Wikia/selenium-tests/pull/1014

**Comment by WikiaTech** [comment]
SonarQube analysis reported 3 issues:
* MAJOR 1 major
* MINOR 2 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Remove this unused import 'com.wikia.webdriver.common.contentpatterns.PageContent'.](https://github.com/Wikia/selenium-tests/blob/ef4cdccdf957875fa3d314d13297a9ee35e9dc61/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wikipage/WikiArticlePageObject.java#L3) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AUselessImportCheck)
* MINOR [Remove this unused import 'com.wikia.webdriver.pageobjectsfactory.pageobject.WikiBasePageObject'.](https://github.com/Wikia/selenium-tests/blob/ef4cdccdf957875fa3d314d13297a9ee35e9dc61/src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Layout.java#L6) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AUselessImportCheck)
* MAJOR [2 duplicated blocks of code must be removed.](https://github.com/Wikia/selenium-tests/blob/ef4cdccdf957875fa3d314d13297a9ee35e9dc61/src/test/java/com/wikia/webdriver/testcases/imageservingtests/ImageStorageTests.java) [rule](http://sonar-s1/coding_rules#rule_key=common-java%3ADuplicatedBlocks)

**Pull request merged**
