### PR TITLE
ADEN-5955 Fixed ads-mercury-providers-chain job

### PR DESCRIPTION
**Pull request by nandy-andy**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AdsBaseObject.java#L358](https://github.com/Wikia/selenium-tests/blob/80e568408f034024c37fbd118e0de3d2ca65d073/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java#L358): Either log or rethrow this exception. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AdsBaseObject.java#L438](https://github.com/Wikia/selenium-tests/blob/80e568408f034024c37fbd118e0de3d2ca65d073/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java#L438): Either log or rethrow this exception. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AS1166)
1. ![MINOR][MINOR] [MobileAdsDataProvider.java#L143](https://github.com/Wikia/selenium-tests/blob/80e568408f034024c37fbd118e0de3d2ca65d073/src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java#L143): Define a constant instead of duplicating this literal "\"loc\":\"top\"" 8 times. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AS1192)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by fraszczakszymon** [comment]
Should we remove those test cases?
https://github.com/Wikia/selenium-tests/blob/80e568408f034024c37fbd118e0de3d2ca65d073/src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java#L617-L627
https://github.com/Wikia/selenium-tests/blob/80e568408f034024c37fbd118e0de3d2ca65d073/src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java#L426-L432

Also I believe we can remove `InstantGlobals.wgAdDriverEvolve2Countries=[]` from all tests cases

**Comment by WikiaTech** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AdsBaseObject.java#L358](https://github.com/Wikia/selenium-tests/blob/7240b46e006a74d259cf9fea56db7222b6c664a2/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java#L358): Either log or rethrow this exception. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AdsBaseObject.java#L438](https://github.com/Wikia/selenium-tests/blob/7240b46e006a74d259cf9fea56db7222b6c664a2/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java#L438): Either log or rethrow this exception. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AS1166)
1. ![MINOR][MINOR] [MobileAdsDataProvider.java#L143](https://github.com/Wikia/selenium-tests/blob/7240b46e006a74d259cf9fea56db7222b6c664a2/src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java#L143): Define a constant instead of duplicating this literal "\"loc\":\"top\"" 8 times. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AS1192)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by nandy-andy** [comment]
We agreed to change mentioned test once we have a fallback-provider (prebid.js provider? //cc @nefretete): https://github.com/Wikia/selenium-tests/blob/80e568408f034024c37fbd118e0de3d2ca65d073/src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java#L617-L627

**Pull request merged**
