### PR TITLE
CONCF 803 | Add test CCT12

### PR DESCRIPTION
**Pull request by tomasznapieralski**
Algorithm:
* open http://mercurycc.wikia.com/
* tap on curated content item called "Broken"
* check that url is on /
* check that alert appeared

### CODE REVIEW

**Comment by justnpT** [comment]
LGTM

**Comment by Warkot** [comment]
LGTM, but please create ticket for including doc-blocks instead of this magic comment strings and add a link to this ticket here as a `TODO`.

**Comment by tomasznapieralski** [comment]
https://wikia-inc.atlassian.net/browse/CONCF-894

**Comment by Warkot** [comment]
:+1:

**Pull request merged**
