### PR TITLE
ADEN-2529 Remove duplicated GeoEdge functionality

### PR DESCRIPTION
**Pull request by drets**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues:
* BLOCKER 2 blocker
* MAJOR 5 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Either log or rethrow this exception.](https://github.com/Wikia/selenium-tests/blob/2d25507d56a49653100f03f34b4ea6d4d0d7aa99/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L113) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1166)
* BLOCKER [Catch Exception instead of Error.](https://github.com/Wikia/selenium-tests/blob/2d25507d56a49653100f03f34b4ea6d4d0d7aa99/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L104) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1181)
* MAJOR [This block of commented-out lines of code should be removed.](https://github.com/Wikia/selenium-tests/blob/2d25507d56a49653100f03f34b4ea6d4d0d7aa99/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L97) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
* MAJOR [Either log or rethrow this exception.](https://github.com/Wikia/selenium-tests/blob/2d25507d56a49653100f03f34b4ea6d4d0d7aa99/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L104) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1166)
* MAJOR [Either remove or fill this block of code.](https://github.com/Wikia/selenium-tests/blob/2d25507d56a49653100f03f34b4ea6d4d0d7aa99/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L113) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00108)
* MAJOR [Either remove or fill this block of code.](https://github.com/Wikia/selenium-tests/blob/2d25507d56a49653100f03f34b4ea6d4d0d7aa99/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L104) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00108)
* BLOCKER [Catch Exception instead of Error.](https://github.com/Wikia/selenium-tests/blob/2d25507d56a49653100f03f34b4ea6d4d0d7aa99/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L113) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1181)

**Comment by PiotrGackowski** [comment]
LGTM

**Comment by tomasznapieralski** [comment]
LGTM

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues:
* BLOCKER 2 blocker
* MAJOR 5 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Either log or rethrow this exception.](https://github.com/Wikia/selenium-tests/blob/7787d8fc6dda5add9f4252ca9487f5010eb5502c/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L113) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1166)
* BLOCKER [Catch Exception instead of Error.](https://github.com/Wikia/selenium-tests/blob/7787d8fc6dda5add9f4252ca9487f5010eb5502c/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L104) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1181)
* MAJOR [Either log or rethrow this exception.](https://github.com/Wikia/selenium-tests/blob/7787d8fc6dda5add9f4252ca9487f5010eb5502c/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L104) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1166)
* MAJOR [Either remove or fill this block of code.](https://github.com/Wikia/selenium-tests/blob/7787d8fc6dda5add9f4252ca9487f5010eb5502c/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L113) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00108)
* MAJOR [Either remove or fill this block of code.](https://github.com/Wikia/selenium-tests/blob/7787d8fc6dda5add9f4252ca9487f5010eb5502c/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L104) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00108)
* MAJOR [This block of commented-out lines of code should be removed.](https://github.com/Wikia/selenium-tests/blob/7787d8fc6dda5add9f4252ca9487f5010eb5502c/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L97) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
* BLOCKER [Catch Exception instead of Error.](https://github.com/Wikia/selenium-tests/blob/7787d8fc6dda5add9f4252ca9487f5010eb5502c/src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java#L113) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1181)

**Pull request merged**
