### PR TITLE
Categorieseditmode update

### PR DESCRIPTION
**Pull request by sczerwinski-wikia**
Waiting till categoryList is populated

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [VisualEditModePageObject.java#L156](https://github.com/Wikia/selenium-tests/blob/4c2fd5deda96d9c4011d601c4183ad32ea6a44aa/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/VisualEditModePageObject.java#L156): Remove this unused private "verifyComponent" method. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [VisualEditModePageObject.java#L156](https://github.com/Wikia/selenium-tests/blob/1a0afb4e694c86ac07e3be2e7e358678417a2e8a/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/VisualEditModePageObject.java#L156): Remove this unused private "verifyComponent" method. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [VisualEditModePageObject.java#L156](https://github.com/Wikia/selenium-tests/blob/97deef4beb457e0a0e9aeb4e222c92262cea6355/src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/VisualEditModePageObject.java#L156): Remove this unused private "verifyComponent" method. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by nikodamn** [comment]
Build passed on this branch, thus I'm merging these changes.

**Pull request merged**
