### PR TITLE
Added a check for current email NOT equals to new email

### PR DESCRIPTION
**Pull request by ludwikkazmierczak**
Added a simple check if 'new email' is not the same as 'current email' - in this situation change will not trigger the mail change confirmation e-mail, and that what was causing the QAART-703 issue.

### CODE REVIEW

**Comment by tomasznapieralski** [comment]
LGTM

**Comment by justnpT** [comment]
Please check if this fixes the tests by https://wikia-inc.atlassian.net/browse/QAART-703 and if yes, remove the related issue id from the affected tests

**Comment by ludwikkazmierczak** [comment]
I'm in the middle of checking that

**Comment by ludwikkazmierczak** [comment]
It works on my machine, but I'm waiting for Jenkins results

**Pull request merged**
