### PR TITLE
SUS-923 Removed wam page test for removed feature

### PR DESCRIPTION
**Pull request by ukaka**
https://wikia-inc.atlassian.net/browse/SUS-923

* removed test that compares selected tab and header as header is not visible on the page anymore

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Remove this unused import 'com.wikia.webdriver.common.core.Assertion'.](https://github.com/Wikia/selenium-tests/blob/320103b252fbd1e5ee50a8b4744d1fc8186abd6f/src/test/java/com/wikia/webdriver/testcases/wampagetests/WamPageTests.java#L3) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Remove this unused import 'com.wikia.webdriver.common.core.Assertion'.](https://github.com/Wikia/selenium-tests/blob/a5f2286847a52c1050855b34113bff49cc81594c/src/test/java/com/wikia/webdriver/testcases/wampagetests/WamPageTests.java#L3) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Remove this unused import 'com.wikia.webdriver.common.core.Assertion'.](https://github.com/Wikia/selenium-tests/blob/5d783fe0a93671248ad5a3dde99af21f431dc813/src/test/java/com/wikia/webdriver/testcases/wampagetests/WamPageTests.java#L3) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by nikodamn** [comment]
LGTM

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Remove this unused import 'com.wikia.webdriver.common.core.Assertion'.](https://github.com/Wikia/selenium-tests/blob/0462b7637b13b69456dff8569ef645ec688fe13e/src/test/java/com/wikia/webdriver/testcases/wampagetests/WamPageTests.java#L3) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AUselessImportCheck)

**Pull request merged**
