### PR TITLE
ADEN-7750 Flaky Sound test removed

### PR DESCRIPTION
**Pull request by emadry**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [TestAdsFeaturedVideoSound.java#L37](https://github.com/Wikia/selenium-tests/blob/0880361b1721c6b0bb85ecdbc78b0b8c0ccd8dee/src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsFeaturedVideoSound.java#L37): Remove this unused private "verifyFeaturedVideoWithSound" method. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [TestAdsFeaturedVideoSound.java#L48](https://github.com/Wikia/selenium-tests/blob/0880361b1721c6b0bb85ecdbc78b0b8c0ccd8dee/src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsFeaturedVideoSound.java#L48): Remove this unused private "verifyFeaturedVideoWithoutSound" method. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MINOR][MINOR] [TestAdsFeaturedVideoSound.java#L5](https://github.com/Wikia/selenium-tests/blob/0880361b1721c6b0bb85ecdbc78b0b8c0ccd8dee/src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsFeaturedVideoSound.java#L5): Remove this unused import 'com.wikia.webdriver.common.core.annotations.UnsafePageLoad'. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AUselessImportCheck)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [TestAdsFeaturedVideoSound.java#L36](https://github.com/Wikia/selenium-tests/blob/ccacc09ee4dfa5ddb00654693722b53915bc273c/src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsFeaturedVideoSound.java#L36): Remove this unused private "verifyFeaturedVideoWithSound" method. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [TestAdsFeaturedVideoSound.java#L47](https://github.com/Wikia/selenium-tests/blob/ccacc09ee4dfa5ddb00654693722b53915bc273c/src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsFeaturedVideoSound.java#L47): Remove this unused private "verifyFeaturedVideoWithoutSound" method. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by emadry** [comment]
Method listed by Sonar is used

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [TestAdsFeaturedVideoSound.java#L36](https://github.com/Wikia/selenium-tests/blob/942f3bd011807c533f79f1dc831288be9a09bbcc/src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsFeaturedVideoSound.java#L36): Remove this unused private "verifyFeaturedVideoWithSound" method. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [TestAdsFeaturedVideoSound.java#L47](https://github.com/Wikia/selenium-tests/blob/942f3bd011807c533f79f1dc831288be9a09bbcc/src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsFeaturedVideoSound.java#L47): Remove this unused private "verifyFeaturedVideoWithoutSound" method. [rule](http://sonar-s4/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Pull request merged**
