### PR TITLE
catch not supported JS operation exception

### PR DESCRIPTION
**Pull request by ludwikkazmierczak**
ADEN-2566

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* INFO 1 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* INFO [Complete the task associated to this TODO comment.](https://github.com/Wikia/selenium-tests/blob/9b5a811d24aef8719585b0ff2ae699d20db28ec7/src/test/java/com/wikia/webdriver/common/core/elemnt/JavascriptActions.java#L37) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1135)

**Comment by tomasznapieralski** [comment]
LGTM

**Comment by drets** [comment]
If we just enable `JS` for `HtmlUnit` we have:
```
org.openqa.selenium.WebDriverException: Can't execute JavaScript before a page has been loaded!
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'wikias-MacBook-Pro-3.local', ip: '192.168.0.31', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.7.0_71'
Driver info: driver.version: EventFiringWebDriver
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.getPageToInjectScriptInto(HtmlUnitDriver.java:729)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.executeScript(HtmlUnitDriver.java:668)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:102)
	at com.sun.proxy.$Proxy27.executeScript(Unknown Source)
	at com.wikia.webdriver.common.core.elemnt.JavascriptActions.execute(JavascriptActions.java:39)
	at com.wikia.webdriver.common.logging.PageObjectLogging.beforeNavigateTo(PageObjectLogging.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openqa.selenium.support.events.EventFiringWebDriver$1.invoke(EventFiringWebDriver.java:79)
	at com.sun.proxy.$Proxy26.beforeNavigateTo(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:159)
	at com.wikia.webdriver.testcases.adstests.TestIVW2AnalyticsProvider.testIVW2AnalyticsProvider(TestIVW2AnalyticsProvider.java:24)
```
and test would fail again :crying_cat_face: 

I am not sure that it's good solution, but for now I don't know the better one as well as why we need to execute JS before each navigation step.

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* INFO 1 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* INFO [Complete the task associated to this TODO comment.](https://github.com/Wikia/selenium-tests/blob/9b5a811d24aef8719585b0ff2ae699d20db28ec7/src/test/java/com/wikia/webdriver/common/core/elemnt/JavascriptActions.java#L37) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1135)

**Pull request merged**
