### PR TITLE
Aden 4135

### PR DESCRIPTION
**Pull request by jacekjursza**
* add new test for enable SP by wgCountry var
* add new test for "hop to taboola" in top leaderboard

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Define a constant instead of duplicating this literal "adUnitId" 5 times.](https://github.com/Wikia/selenium-tests/blob/1b5acf46cb99febea512c1beea462b92f6cec027/src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java#L1131) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AS1192)

**Comment by nandy-andy** [comment]
LGTM :+1:

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Define a constant instead of duplicating this literal "adUnitId" 5 times.](https://github.com/Wikia/selenium-tests/blob/b145171fd574d38359a51b75cbb58794266d2f98/src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java#L1131) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Define a constant instead of duplicating this literal "adUnitId" 5 times.](https://github.com/Wikia/selenium-tests/blob/2e19ff13d258591641a6f6863dd9db1b4a8ef38e/src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java#L1131) [rule](http://sonar-s1/coding_rules#rule_key=squid%3AS1192)

**Comment by bulaszenko** [comment]
LGTM

**Pull request merged**
